# version: "3.8"

services:

  # The Context Broker (Orion-LD)
  orion:
    image: fiware/orion-ld #:1.5.1
    container_name: orion
  # expose:
  #   - "1026"
    depends_on:
      - mongo
    environment:
      - OAUTH2_ENABLED=true
      - OAUTH2_TOKEN_ENDPOINT=${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/token
      - OAUTH2_CLIENT_ID=${ORION_CLIENT_ID}
      - OAUTH2_CLIENT_SECRET=${ORION_CLIENT_SECRET}
    command: -db orionld -logLevel DEBUG -forwarding -dbhost mongo   
    healthcheck:
      test: curl -sf http://localhost:1026/version
  # networks: # to be replicated in each container
  #   - dedalus-net
    
  # DB for the Context Broker (MongoDB)
  mongo:
    image: mongo:5 #:4.4
    container_name: db-mongo
    command: --nojournal
    volumes:
      - mongo-db:/data/db
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    healthcheck:
      test: mongo --eval "db.adminCommand('ping')" --quiet

  # Context Provider and Swagger GUI (Node.js)
  node-red:
    image: nodered/node-red #:3.1.9-18
    hostname: ${HOSTNAME:-node-red}
    container_name: node-red
  # restart: always
    ports:
      - "${CP_PORT:-1880}:1880"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - ganache
      - keycloak
      - mosquitto
    environment:
      - TZ=Europe/Amsterdam
    user: root
    entrypoint: bash -c "cd /data; npm i --unsafe-perm --no-update-notifier --no-fund --only=production; cd /usr/src/node-red; ./entrypoint.sh"
    volumes:
      - ./node-red/data:/data
      - .:/home/node-red

  # Identity Manager (Keycloak)
  keycloak:
    image: quay.io/keycloak/keycloak #:23.0.6
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN_USERNAME}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    command: start-dev --import-realm
    volumes:
      - ./configs/realm-config.json:/opt/keycloak/data/import/realm-config.json
      - keycloak-data:/opt/keycloak/data/
    healthcheck:
      test: exec 3<>/dev/tcp/127.0.0.1/9000; echo -e 'GET /health/ready HTTP/1.1\r\nHost: localhost:9000\r\nConnection: close\r\n\r\n' >&3;cat <&3 | grep -q '\"status\": \"UP\"' && exit 0 || exit 1

  # Web Server for NGSI-LD @context files and reverse proxy (Nginx)
  nginx:
    image: nginx #:1.25.4
    container_name: nginx
    ports:
      - "${WS_PORT:-80}:80"
    depends_on:
      - keycloak
      - orion
      - node-red
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/usr/share/nginx/html
    healthcheck:
      test: curl -sf http://localhost/data-models/ngsi-context.jsonld

  # Blockchain with deployed PoE smart contract
  ganache:
  # image: trufflesuite/ganache #:v7.9.2
    image: hybuild/ganache #:poe9 #:etk4
    hostname: rpc
    container_name: ganache
  # restart: always
    ports:
      - "7545:7545"
  # command: --database.dbPath /db --server.host 0.0.0.0 --server.port 7545 --wallet.mnemonic "visit carpet logic blame furnace confirm rebel deliver medal mean illness error"
    volumes:
      - ganache-db:/db
    healthcheck:
      test: node -e "fetch('http://localhost:7545', { method:'POST', headers:{ 'content-type':'application/json' }, body:JSON.stringify({ id:1, jsonrpc:'2.0', method:'eth_blockNumber' }) }).then(res => res.json()).then(res => process.exit(0)).catch(err => process.exit(1));"

  # MQTT Broker (MosQuiTTo)
  mosquitto:
    image: eclipse-mosquitto #:2.0.15
    hostname: mqtt
    container_name: mosquitto
  # restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    command: mosquitto -c /mosquitto-no-auth.conf
  # volumes:
  #   - mosquitto-data:/mosquitto/data  
  #   - mosquitto-log:/mosquitto/log  
    healthcheck:
      test: mosquitto_sub -t '$$SYS/#' -C 1 | grep -v Error

  # docker exec -it mosquitto mosquitto_sub -h mosquitto -t "/#"
  # docker exec -it mosquitto mosquitto_pub -h mosquitto -m "Hello world!" -t "/test"

volumes:
  keycloak-data: ~
  mongo-db: ~

# networks:
#   dedalus-net:
#     name: dedalus-net
#     driver: bridge