services:
  nginx:
    image: nginx #:1.25.4
    container_name: samothrace-nginx
    depends_on:
      - marketplace-core
      - marketplace-gui
      - samothrace-dashboard
      - gres-optimizator-estimator
    restart: always
    networks:
      - samothrace-network
    ports:
      - "80:80"
      - "4443:443"
      - "4173:4173"
      - "8080:8080"
      - "3000:3000"
      - "5000:5000"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: ["/bin/sh", "-c", "/docker-entrypoint.sh nginx & while true; do [ -d /var/www/certbot/reload ] && nginx -s reload && rm -rf /var/www/certbot/reload; sleep 60; done"]

  # Initialize decommenting "command", commenting out "entrypoint" and running: docker compose up samothrace-certbot
  certbot:
    image: certbot/certbot #:v2.10.0
    container_name: samothrace-certbot
    depends_on:
      - nginx
    restart: always
    networks:
      - samothrace-network
    volumes:
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/var:/var/lib/letsencrypt
    entrypoint: ["/bin/sh", "-c", "trap exit TERM; while :; do certbot certonly --webroot -w /var/www/certbot/ -d samothrace.duckdns.org --register-unsafely-without-email --agree-tos --keep --non-interactive --deploy-hook 'mkdir /var/www/certbot/reload'; sleep 12h & wait $${!}; done"]
    healthcheck:
      test: ["CMD-SHELL", "find /etc/letsencrypt/live -type d -empty -exec false {} +"]

  postgres:
    image: postgres:16.1-alpine
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: marketplace
    networks:
      - samothrace-network
  # ports:
  #   - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    restart: always
    container_name: keycloak
    command: start-dev --import-realm
    # expose:
    #   - "8081"
    #   - "8443"
    networks:
      - samothrace-network
    ports:
      - "8443:8443"
      - "8081:8081"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_FEATURES=preview
      - KC_HTTP_PORT=8081
      - KC_HTTPS_PORT=8443
      - KC_HTTPS_CERTIFICATE_FILE=/opt/keycloak/conf/server.crt.pem
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/opt/keycloak/conf/server.key.pem
    volumes:
      - keycloak_data:/opt/keycloak/data/
      - ./keycloak/samothrace-marketplace-realm.json:/opt/keycloak/data/import/samothrace-marketplace-realm.json
      - ./keycloak/login:/opt/keycloak/themes/samothrace-theme/login
      - ./certbot/conf/live/samothrace.duckdns.org/fullchain.pem:/opt/keycloak/conf/server.crt.pem
      - ./certbot/conf/live/samothrace.duckdns.org/privkey.pem:/opt/keycloak/conf/server.key.pem

  marketplace-core:
    image: scsx/samothrace-marketplace-core:1.0.0
    restart: always
    container_name: marketplace-core
    networks:
      - samothrace-network
  # ports:
  #   - "8080:8080"
    depends_on:
      - postgres
      - keycloak
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/marketplace
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI: https://samothrace.duckdns.org:8443/realms/samothrace-marketplace
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: http://keycloak:8081/realms/samothrace-marketplace/protocol/openid-connect/certs
      KEYCLOAK_SERVER-URL: https://samothrace.duckdns.org:8443
      KEYCLOAK_REALM: samothrace-marketplace
      KEYCLOAK_CLIENTID: marketplace-core

  marketplace-gui:
    image: lorenzocristoforieng/samothrace-marketplace:1.0.1
    restart: always
    container_name: marketplace-gui
    networks:
      - samothrace-network
    expose:
      - "4173"
  # ports:
  #   - "4173:4173"
    depends_on:
      - postgres
      - keycloak
      - marketplace-core

  gres-optimizator-estimator:
    image: lorenzocristoforieng/gres-consumption-production_toolkit:1.0.1
    restart: always
    container_name: gres-optimizator-estimator
    networks:
      - samothrace-network
    expose:
      - "5000"
  # ports:
  #   - "5000:5000"

  samothrace-dashboard:
    image: scsx/samothrace-dashboard:latest
    restart: always
    container_name: samothrace-dashboard
    networks:
      - samothrace-network
    expose:
      - "3000"
  #  ports:
  #    - "3000:3000"
    depends_on:
      - gres-optimizator-estimator
    volumes:
      - samothrace-dashboard-env:/env
    environment:
      REACT_APP_SAMOTHRACE_URL: https://samothrace.eu
      REACT_APP_NG_EU_URL: https://next-generation-eu.europa.eu
      REACT_APP_MUR_URL: https://www.mur.gov.it/it
      REACT_APP_SAMOTHRACE_LINKEDIN: https://www.linkedin.com/company/fondazione-samothrace
      REACT_APP_SAMOTHRACE_FACEBOOK: https://www.facebook.com/people/Fondazione-Samothrace/61550482396845
      REACT_APP_MARKETPLACE_URL: https://samothrace.duckdns.org:4173
      REACT_APP_EC_PLATFORM_URL: https://netaportal-master.netasaas.cloudeng.it/auth/external/do-login
      REACT_APP_EC_OPTIMISER_URL: https://samothrace.duckdns.org:5000

volumes:
  postgres-data:
  keycloak_data:
  marketplace_gui_env:
  samothrace-dashboard-env:

networks:
  samothrace-network:
