server {
    listen      80;
    listen [::]:80;
    server_name samothrace.duckdns.org;

    location ~ /.well-known/acme-challenge {
      allow all;
      root /var/www/certbot;
    }

    location / {
      return 301 https://$host:4173$request_uri;
    }
}

server {
    listen      4173 ssl;
    listen [::]:4173 ssl;
    server_name samothrace.duckdns.org;

    ssl_certificate   /etc/letsencrypt/live/samothrace.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/samothrace.duckdns.org/privkey.pem;

    location / {
        proxy_pass http://marketplace-gui:4173;
    }
}

server {
    listen      8080 ssl;
    listen [::]:8080 ssl;
    server_name samothrace.duckdns.org;

    ssl_certificate   /etc/letsencrypt/live/samothrace.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/samothrace.duckdns.org/privkey.pem;

    location / {
        proxy_pass http://marketplace-core:8080;
    }
}

server {
    listen      3000 ssl;
    listen [::]:3000 ssl;
    server_name samothrace.duckdns.org;

    ssl_certificate   /etc/letsencrypt/live/samothrace.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/samothrace.duckdns.org/privkey.pem;

    location / {
        proxy_pass http://samothrace-dashboard:3000;
    }
}

server {
    listen      5000 ssl;
    listen [::]:5000 ssl;
    server_name samothrace.duckdns.org;

    ssl_certificate   /etc/letsencrypt/live/samothrace.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/samothrace.duckdns.org/privkey.pem;

    location / {
        proxy_pass http://gres-optimizator-estimator:5000;
    }
}