# renew_before_expiry = 30 days
version = 3.1.0
archive_dir = /etc/letsencrypt/archive/engsep.duckdns.org
cert = /etc/letsencrypt/live/engsep.duckdns.org/cert.pem
privkey = /etc/letsencrypt/live/engsep.duckdns.org/privkey.pem
chain = /etc/letsencrypt/live/engsep.duckdns.org/chain.pem
fullchain = /etc/letsencrypt/live/engsep.duckdns.org/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = a405fd669b9ba899895c08d0c7f48ae7
server = https://acme-v02.api.letsencrypt.org/directory
authenticator = standalone
key_type = ecdsa
