# renew_before_expiry = 30 days
version = 3.1.0
archive_dir = /etc/letsencrypt/archive/samothrace.duckdns.org
cert = /etc/letsencrypt/live/samothrace.duckdns.org/cert.pem
privkey = /etc/letsencrypt/live/samothrace.duckdns.org/privkey.pem
chain = /etc/letsencrypt/live/samothrace.duckdns.org/chain.pem
fullchain = /etc/letsencrypt/live/samothrace.duckdns.org/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 10544463b690eea5d27ee793fa4856a1
server = https://acme-staging-v02.api.letsencrypt.org/directory
authenticator = standalone
key_type = ecdsa
